config/routes.rb
Rails.application.routes.draw do

#認証機能に関して
  devise_for :admins, controllers: {
    registrations: 'admins/registrations',
    sessions: 'admins/sessions',
    passwords: 'admins/passwords'
  }
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }

#管理者権限
  namespace :admins do
  	resources :users, only: [:index, :show, :edit, :update] do
      member do
        patch :toggle
      end
    end
  	resources :genres, only: [:index, :create, :update] do
      member do
        patch :enable
        patch :disable
      end
    end

  	resources :products, except: [:destroy]
  	resources :orders, only: [:index, :update, :show]
  end

#顧客表示部分

	resources :users, only: [:show, :edit, :update] do
    member do
      patch :leave
    end
  end
	resources :products, only: [:show]
	resources :cart_items, only: [:index, :create, :destroy]

  get 'orders/finish' => 'orders#finish'
	resources :orders, only: [:index, :show, :new, :create] do
    member do
      get :confirm
    end
  end
	resources :ship_to_addresses, only: [:create, :index, :destroy, :edit, :update]

  get 'home/about' => 'home#about'

  delete :cart_items, to: 'cart_items#destroy_all'
  patch :cart_items, to: 'cart_items#update_all'

  get 'admins' => 'admins/home#top'

  root to: 'products#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  #配送先との紐付け
  has_many :ship_to_addresses, dependent: :destroy
  #カートの商品との紐付け
  has_many :cart_items, dependent: :destroy
  #注文履歴との紐付け
  has_many :orders, dependent: :destroy

  #validation
  validates :last_name_kana, format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: 'はカタカナで入力して下さい。'}
  validates :first_name_kana, format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: 'はカタカナで入力して下さい。'}
  validates :postal_code, format: /\A[0-9]+\z/
  validates :phone, format:/\A[0-9]+\z/
end

app/controllers/admins/users_controller.rb
class Admins::UsersController < ApplicationController
  before_action :authenticate_admin!

  def index
  	@users = User.all
  end

  def show
  	@user = User.find(params[:id])
  end

  def edit
  	@user = User.find(params[:id])
  end

  def update
  	@user = User.find(params[:id])
  	if @user.update(user_params)
       flash[:success] = "更新に成功しました"
       redirect_to admins_user_path(@user)
    else
       flash[:warning] = "入力内容を確認してください"
       render :edit
    end
  end

  def toggle
  	@user = User.find(params[:id])

  	if @user.is_deleted?
  		  @user.is_deleted = false
  	else
  		  @user.is_deleted = true
  	end
        @user.save
        redirect_to edit_admins_user_path(@user)
  end

  private
  	def user_params
  		params.require(:user).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :phone, :email, :is_deleted)
  	end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  #GET /resource/password/edit?reset_password_token=abcdef
  def edit
     super
 end

  #PUT /resource/password
  def update
     super
 end

  protected

  def after_resetting_password_path_for(resource)
     super(resource)
  end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

#ログインユーザーのみ
  before_action :authenticate_user!
#退会済みユーザー
  before_action :user_is_deleted
#@userの値のセット
  before_action :set_user

# 顧客詳細画面
  def show
  # 他のuserのアクセス阻止
    unless current_user.nil? || current_user.id == @user.id
      flash[:warning] = "アクセス権がありません"
      redirect_to user_path(current_user)
    end
  end
# 顧客編集画面
  def edit
    # 他のuserのアクセス阻止
    unless current_user.nil? || current_user.id == @user.id
      flash[:warning] = "アクセス権がありません"
      redirect_to user_path(current_user)
    end
  end

# 顧客編集画面で変更された内容を保存
  def update
  	if @user.update(user_params)
        flash[:success] =  "更新に成功しました"
        redirect_to user_path(current_user)
    else
      flash[:warning] = "入力内容を確認してください"
      render :edit
    end
  end

#退会機能
  def leave
      @user.is_deleted = true
      @user.save
      flash[:success] =  "さようなら、#{@user.first_name}さん"
      redirect_to destroy_user_session_path
  end

  private
# @userの値をセット
  	def set_user
  		@user = User.find(params[:id])
  	end

# ストロングパラメーター
  	def user_params
  		params.require(:user).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :address, :postal_code, :phone, :email, :is_deleted)
  	end

#退会済みユーザーへの対応
    def user_is_deleted
      if user_signed_in? && current_user.is_deleted?
         redirect_to root_path
      end
    end

end

app/helpers/admins/users_helper.rb
module Admins::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="edit-container" style="width:50%; margin: 20px auto; position: relative;">
  <h4 style="margin-bottom: 20px; border-left: 2px solid #2D6F4C; padding: 10px;">ユーザー情報編集</h4>
<%= form_for(@user, url:user_path(@user), method: :patch) do |f| %>
       <%= link_to leave_user_path(@user), method: :patch, data: { confirm: '本当に退会しますか？' } do %>
              <span class="btn btn-danger" style="position: absolute; top: 30px; right: 50px;">退会する</span>
       <% end %>
    <div class="row" style="height: 20px;"></div>

<div class="form-group">
    <label>姓</label>
    <%= f.text_field :last_name, autofocus: true, autocomplete: "last_name", style: "margin;"  %>
    <label>名</label>
    <%= f.text_field :first_name, autofocus: true, autocomplete: "first_name" %>
  </div>

  <div class="form-group">
    <label>セイ</label>
    <%= f.text_field :last_name_kana, autofocus: true, autocomplete: "last_name_kana" %>
    <label>メイ</label>
    <%= f.text_field :first_name_kana, autofocus: true, autocomplete: "first_name_kana" %>
  </div>

  <div class="form-group">
    <label>郵便番号（ハイフンなし）</label>
    <%= f.text_field :postal_code, autofocus: true, autocomplete: "postal_code" %>
  </div>

   <div class="form-group">
    <label>住所</label>
    <%= f.text_field :address, autofocus: true, autocomplete: "address", style: "width: 80%;" %>
  </div>

  <div class="form-group">
    <label>電話番号</label>
    <%= f.telephone_field :phone, autofocus: true, autocomplete: "phone" %>
  </div>

  <div class="form-group">
    <label>メールアドレス</label>
    <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
  </div>
  <hr>
  <div style="text-align:center;">
    <%= f.submit "変更を保存する", class:"btn btn-success", style: "display:inline-block" %>
  </div>

  <%= link_to user_path(@user) do %>
      <span class="glyphicon glyphicon-chevron-left">マイページ</span>
  <% end %>

<% end %>
</div>

app/views/users/show.html.erb
<div class="show-container" style="width:50%; margin: 20px auto;">
	<h4 style="margin-bottom: 20px; border-left: 2px solid #2D6F4C; padding: 10px;">マイページ</h4>

	<table class="table table-condensed">
		<tbody>
			<tr>
				<th style="background-color: #dad7d7; border-bottom: 1px solid #fff;">名前</th>
				<td><%= @user.last_name %> <%= @user.first_name %></td>
			</tr>
			<tr>
				<th style="background-color: #dad7d7; border-bottom: 1px solid #fff;">フリガナ</th>
				<td><%= @user.last_name_kana %> <%= @user.first_name_kana %></td>
			</tr>
			<tr>
				<th style="background-color: #dad7d7; border-bottom: 1px solid #fff;">郵便番号</th>
				<td>〒 <%= @user.postal_code %></td>
			</tr>
			<tr>
				<th style="background-color: #dad7d7; border-bottom: 1px solid #fff;">住所</th>
				<td><%= @user.address %></td>
			</tr>
			<tr>
				<th style="background-color: #dad7d7; border-bottom: 1px solid #fff;">電話番号</th>
				<td><%= @user.phone %></td>
			</tr>
			<tr>
				<th style="background-color: #dad7d7; border-bottom: 1px solid #fff;">メールアドレス</th>
				<td style="border-bottom: 1px solid #dad7d7;"><%= @user.email %></td>
			</tr>

		</tbody>
	</table>
	<%= link_to '登録情報を編集する', edit_user_path(@user), class:"btn btn-info" %>
	<%= link_to 'パスワードを編集する', edit_user_registration_path, class:"btn btn-success" %>
	<hr>
	<h4 style="margin-bottom: 20px; border-left: 2px solid #2D6F4C; padding: 10px;">配送先</h4>
		<%= link_to ship_to_addresses_path do %>
			一覧を見る<span class="glyphicon glyphicon-chevron-right"></span>
		<% end %>
	<hr>
	<h4 style="margin-bottom: 20px; border-left: 2px solid #2D6F4C; padding: 10px;">注文履歴</h4>
		<%= link_to orders_path(id: @user.id) do %>
			一覧を見る<span class="glyphicon glyphicon-chevron-right"></span>
		<% end %>
	<hr>
</div>