config/routes.rb
Rails.application.routes.draw do

#認証機能に関して
  devise_for :admins, controllers: {
    registrations: 'admins/registrations',
    sessions: 'admins/sessions',
    passwords: 'admins/passwords'
  }
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }

#管理者権限
  namespace :admins do
  	resources :users, only: [:index, :show, :edit, :update] do
      member do
        patch :toggle
      end
    end
  	resources :genres, only: [:index, :create, :update] do
      member do
        patch :enable
        patch :disable
      end
    end

  	resources :products, except: [:destroy]
  	resources :orders, only: [:index, :update, :show]
  end

#顧客表示部分

	resources :users, only: [:show, :edit, :update] do
    member do
      patch :leave
    end
  end
	resources :products, only: [:show]
	resources :cart_items, only: [:index, :create, :destroy]

  get 'orders/finish' => 'orders#finish'
	resources :orders, only: [:index, :show, :new, :create] do
    member do
      get :confirm
    end
  end
	resources :ship_to_addresses, only: [:create, :index, :destroy, :edit, :update]

  get 'home/about' => 'home#about'

  delete :cart_items, to: 'cart_items#destroy_all'
  patch :cart_items, to: 'cart_items#update_all'

  get 'admins' => 'admins/home#top'

  root to: 'products#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
	belongs_to :user
	belongs_to :product

	validates :quantity, presence: true


end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
#ログインユーザーのみ閲覧可
  before_action :authenticate_user!
#退会済みユーザーは閲覧不可
  before_action :user_is_deleted

  def index
    @cart_items = current_user.cart_items
    @total_price = @cart_items.sum(:price)
  end

  def create
    @cart_item = CartItem.new(item_params)
    @cart_item.user_id = current_user.id
    #税抜の小計価格を設定
    @cart_item.price = @cart_item.product.price * @cart_item.quantity
    @cart_item.save
    redirect_to cart_items_path
  end

  #ある商品の入ったカートを空にする
  def destroy
    @cart_item = CartItem.find(params[:id])
  	@cart_item.destroy
    redirect_to cart_items_path
  end

  #カートを空にする
  def destroy_all
  	@cart_items = current_user.cart_items
    @cart_items.destroy_all
    redirect_to cart_items_path
  end

  #再計算する
  def update_all
  @items = current_user.cart_items

  @items.each do |item|
        item.quantity = params[:quantity][item.id.to_s].to_i
        item.price = item.quantity * item.product.price
        item.save
        flash[:success] =  "更新に成功しました"
  end
        flash[:warning] = "入力内容を確認してください"
        redirect_to cart_items_path
  end

  private
    def item_params
      params.require(:cart_item).permit(:user_id, :product_id, :quantity, :price)
    end

    #退会済みユーザーへの対応
    def user_is_deleted
      if user_signed_in? && current_user.is_deleted?
         redirect_to root_path
      end
    end
end

app/helpers/cart_items_helper.rb
module CartItemsHelper

end

app/views/cart_items/index.html.erb
<div class="cart_container" style="width:90%; margin: 20px auto; position:relative;">

<strong style="font-size:18px;">
	<img src="/assets/cart_icon.jpg" style="display:inline-block; height: 25px;">
	ショッピングカート
</strong>

<div class="row" style="width:100%; height:20px;"></div>

<div style="position:absolute; top: 30px; right: 0;">
	<%= link_to cart_items_path, method: :delete do %>
		<span class="btn btn-danger">カートを空にする</span>
	<% end %>
</div>

<%= form_for cart_items_path, method: :patch do |f| %>
<span style="color:#266846;">表示されている価格は全て税込です。</span>
<table class="table table-bordered">
	<tr style="background:#dad7d7; border: 1px solid #fff;">
		<th>商品名</th>
		<th>単価</th>
		<th>数量</th>
		<th>小計</th>
		<th></th>
	</tr>
 <% @cart_items.each do |item| %>
	<tr>
		<td>
			<%= attachment_image_tag item.product, :image, :fill, 50, 50 %>
			<%= item.product.name %>
		</td>
		<td>
 			<%= hidden_field_tag :product_price, item.product.price %>
			<%= addTax(item.product.price) %>
		</td>
		<td>
			<%= hidden_field_tag "product_id[#{item.id}]", item.product_id %>
			<%= number_field_tag "quantity[#{item.id}]", item.quantity, in: 1..10 %>
		</td>
		<td>
			<%= hidden_field_tag "price[#{item.id}]", item.price %>
			<%= addTax(item.price) %>
		</td>
		<td><%= link_to '削除する', cart_item_path(item), method: :delete %></td>
	</tr>
 <% end %>
</table>

<div class="row">
	<div class="col-xs-4">
		<%= link_to root_path do %>
			<span class="btn btn-info glyphicon glyphicon-chevron-left">買い物を続ける</span>
		<% end %>
	</div>
	<div class="col-xs-4 pull-right">
		<table class="table table-striped">
			<tr style="background:#dad7d7; border: 1px solid #fff;"><th>合計金額</th></tr>
			<tr><td><%= addTax(@total_price) %></td></tr>
		</table>

		<div class="pull-right">
			<%= f.submit '再計算する', class:"btn btn-default", data: {toggle:"tooltip", placement:"left"}, title:"数量を変更したらクリック" %>
		</div>
<% end %>

	</div>

</div>



<!-- カートに商品が入っていたら表示させる -->

	<% if @cart_items.blank? %>
		<% else %>
		<div class="text-center">
			<%= link_to '購入に進む', new_order_path, class:"btn btn-success" %>
		</div>
	<% end %>

</div>



<script>
	$(function () {
	$('[data-toggle="tooltip"]').tooltip();
});
</script>

app/views/cart_items/show.html.erb
<h4>注文情報確認</h4>

<table class="table table-striped">
	<tr>
		<th>商品名</th>
		<th>単価（税込）</th>
		<th>数量</th>
		<th>小計</th>
	</tr>
 <% @cart_items.each do |item| %>
	<tr>
		<td><%= item.product.name %></td>
		<td><%= addTax(item.product.price) %></td>
		<td><%= item.quantity %></td>
		<td><%= totalPrice(addTax(item.product.price),item.quantity) %></td>
	</tr>
 <% end %>
</table>