config/routes.rb
Rails.application.routes.draw do

#認証機能に関して
  devise_for :admins, controllers: {
    registrations: 'admins/registrations',
    sessions: 'admins/sessions',
    passwords: 'admins/passwords'
  }
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }

#管理者権限
  namespace :admins do
  	resources :users, only: [:index, :show, :edit, :update] do
      member do
        patch :toggle
      end
    end
  	resources :genres, only: [:index, :create, :update] do
      member do
        patch :enable
        patch :disable
      end
    end

  	resources :products, except: [:destroy]
  	resources :orders, only: [:index, :update, :show]
  end

#顧客表示部分

	resources :users, only: [:show, :edit, :update] do
    member do
      patch :leave
    end
  end
	resources :products, only: [:show]
	resources :cart_items, only: [:index, :create, :destroy]

  get 'orders/finish' => 'orders#finish'
	resources :orders, only: [:index, :show, :new, :create] do
    member do
      get :confirm
    end
  end
	resources :ship_to_addresses, only: [:create, :index, :destroy, :edit, :update]

  get 'home/about' => 'home#about'

  delete :cart_items, to: 'cart_items#destroy_all'
  patch :cart_items, to: 'cart_items#update_all'

  get 'admins' => 'admins/home#top'

  root to: 'products#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_adminfooter.html.erb
<header>
<% if admin_signed_in? %>
	<footer>
		<div class="container">
			<img src="/assets/logo.jpg" alt="非表示", style = "height:60px; margin: 30px 5px;">
		</div>
	</footer>
<% end %>
<</

app/views/layouts/_adminheader.html.erb
<!-- admin側のheader -->
<style>
	#header {
		width: 100%;
		height: 181px;
		border-bottom: 1px solid #dad7d7;
		padding: 20px;
	}
	ul {
		list-style: none;
	}

	li {
		display: inline-block;
		color:#694d49;
		margin-right: 10px;
	}
</style>

<div id="header">
<p>管理者ページ</p>
<%= link_to admins_path do %>
	<img src="/assets/logo.jpg" style="height:100px; display:block; margin: 0 auto;">
<% end %>

<div class="box" style="margin: 0 auto; text-align: center;">
	<ul>
		<li><%=link_to '商品一覧', admins_products_path %></li>
		<li><%=link_to '会員一覧', admins_users_path %></li>
		<li><%=link_to '注文履歴一覧', admins_orders_path %></li>
		<li><%=link_to 'ジャンル管理', admins_genres_path %></li>
		<li><%=link_to 'ログアウト', destroy_admin_session_path, method: :delete %></li>
	</ul>
</div>
</div>

app/views/layouts/_footer.html.erb
<style>
	.link_box {
		position: absolute;
		top: 10px;
		right: 40px;
		text-align: center;
	}

	.icon {
		display: inline-block;
		width: 30px;
		height: 30px;
		margin-right: 10px;
		margin-top: 5px;
	}

	p {
		color: #836159;
	}

</style>



<div style="width:100%; position:relative;">

	<img src="/assets/logo.jpg" alt="非表示", style = "height:80px;">


	<div class="link_box">
		<span id="text">share us!</span><br>
		 <%= link_to '/' do %>
			<img src="/assets/twitter.jpg" class="icon">
		 <% end %>
		 <%= link_to '/' do %>
			<img src="/assets/facebook.jpg" class="icon">
		<% end %>
		<%= link_to '/' do %>
			<img src="/assets/instagram.jpg" class="icon">
		<% end %>
	</div>

	<p class="text-center">(c) all rights naganocake & team camel</p>

</div>

app/views/layouts/_header.html.erb
<style>
	ul {
		list-style: none;
	}

	li {
		display: inline-block;
		color:#694d49;
		margin-right: 10px;
	}
</style>



<div id="header" style="border-bottom:1px solid #dad7d7">

<!-- 退会済みユーザーの場合は表示を変える。 -->
	<% if user_signed_in? && current_user.is_deleted? %>
			<p style="text-align:right; padding: 10px 10px 0 0; color:#694D49;">
				あなたは退会済みです
			</p>
	<% elsif user_signed_in? && !current_user.is_deleted %>
			<p style="text-align:right; padding: 10px 10px 0 0; color:#694D49;">
				ようこそ、
				<%= link_to current_user.first_name, user_path(current_user) %>
				さん
			</p>
	<% end %>

<%= link_to root_path do %>
		<img src="/assets/logo.jpg" style="height:100px; display:block; margin: 0 auto">
<% end %>


<div id="box" style="margin: 0 auto 20px; text-align: center;">
	<% if user_signed_in? && !current_user.is_deleted? %>
<!-- ログイン時表示される内容-->
	<ul>
		<li><%= link_to 'ABOUT US', home_about_path %></li>
		<li><%= link_to 'SHOPPING', cart_items_path %></li>
		<li><%= link_to 'LOGOUT', destroy_user_session_path, method: :delete %></li>
	</ul>

	<% else %>
<!-- ログアウト時に表示される内容 -->
	<ul>
		<li><%= link_to 'ABOUT US', cart_items_path %></li>
		<li><%= link_to 'SIGN UP', new_user_registration_path %></li>
		<li><%= link_to 'LOGIN', new_user_session_path %></li>
	</ul>
	<% end %>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Naganocake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= include_gon %>
    <%= javascript_include_tag 'application' %>
  </head>


  <body>

  <div id="container">
    <header>
        <% if admin_signed_in? %>
            <%= render 'layouts/adminheader' %>
        <% else %>
            <%= render 'layouts/header' %>
        <% end %>
    </header>

    <main>

      <% if flash[:success] %>
          <div class="alert alert-success text-center" role="alert"><%= flash[:success] %></div>
      <% elsif flash[:warning] %>
          <div class="alert alert-warning text-center" role="alert"><%= flash[:warning] %></div>
      <% end %>

        <%= yield %>
    </main>

    <footer>
      <%= render 'layouts/footer'%>
    </footer>

  </div>

  </body>
</html>